### ISSUE TITLE
Milestone 2 Assignment 

### ISSUE THREAD

**Issue by yash225** [adn28/IT490#2]
Each member of the group has read the Messaging, Database, Front End, and Back End chapters.

The group has created a docker-compose.yml file in the group repository that brings up a messaging service, database service, front end service, and back end service.

Front End has a "Hello World" page available on a port accessible from the local host.

Back End can read from and write to a queue on Messaging.

The completion of this milestone is documented through the use of Issues in the group GitHub repository.

**Comment by adn28** [comment]
yea i see it
