### ISSUE TITLE
Milestone 3 

### ISSUE THREAD

**Issue by yash225** [adn28/IT490#3]
Back End can read and write from Database.

Front End has a register new user page and a login page. They do not have to be functional, but the HTML for the page is being served.

Database has a user table in a database on a persistent volume and the database can be accessed by Back End.

Documentation is developed that describes how to use the RabbitMQ management interface to check to see if queues are being created. The documentation is in the form of a README file in any GitHub supported format within the messaging directory.

The completion of this milestone is documented through the use of Issues in the group GitHub repository
____________________________________________________________________________________________________________________________________

Hey guys please try to do each of your part for this milestone!

**Comment by yash225** [comment]
can someone do the back-end part making a connection and reading and writing to database, I have already finished all the milestone part except for the back end can read and write from database!

**Comment by adn28** [comment]
yup

**Comment by adn28** [comment]
complete
