### ISSUE TITLE
Milestone Four

### ISSUE THREAD

**Issue by adn28** [adn28/IT490#4]
1. Have minikube up and running for everyone in the team.
2. Enable Kubernetes thru Docker Desktop in the Settings. There is a enable option. just tick it.
3. configure docker-compose.yml for replication

**Comment by yash225** [comment]
hey guys I am trying to run the files that professor has given to us for replication, but I am getting the error :

ERROR: for d907ff785965_replication_db1_1  Cannot start service db1: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown

ERROR: for db2  Cannot start service db2: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown

ERROR: for db1  Cannot start service db1: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown
ERROR: Encountered errors while bringing up the project.


Let me know if I am doing anything wrong in my code?

**Comment by adn28** [comment]
okay lets see.

**Comment by gac29** [comment]
I'm checking as well.

**Comment by gac29** [comment]
getting the same error here :(

ERROR: for replication_db2_1  Cannot start service db2: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $Starting replication_db1_1 ... error

ERROR: for replication_db1_1  Cannot start service db1: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown

ERROR: for db2  Cannot start service db2: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown

ERROR: for db1  Cannot start service db1: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown
ERROR: Encountered errors while bringing up the project.
Arifs-MacBook-Air:db choudhury$

**Comment by yash225** [comment]
I have pushed the milestone 4 part on GitHub, I was still getting that error on my Mac, but when I tried the same code on windows, it was working.
